# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "Europe/Madrid"
  end

  if Vagrant.has_plugin?("landrush")
    config.landrush.enabled = true
    config.landrush.tld = ''
    config.landrush.guest_redirect_dns = false
  end

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 2048
    virtualbox.cpus = 2
  end

  config.vm.define "yatm" do |yatm|
    yatm.vm.box = "debian/stretch64"
    yatm.vm.hostname = "yatm"
    yatm.vm.network "private_network", type: "dhcp"
    yatm.vm.provision "ansible" do |ansible|
      ansible.galaxy_role_file = "requirements.yml"
      ansible.galaxy_roles_path = "roles"
      ansible.playbook = "yatm.yml"
      ansible.sudo = true
    end
  end

end
